WIP: Http client to retrieve incidences data from all services
swisscovidtravel/conav pull request #9
Opened 2021-03-21 17:36 UTC by livionaef

Han mol ahgfange s vorgebnige Skeleton z implementiere und weiss ned genau öb das so scho funktioniert oder ob ich no sache muess dezuefüege.

In /consume/main.go hani die verschiednige calls als test uf euse server mol ih structs gmappt wo funktioniert (bis uf municipalities wos halt nonig git) aber weiss nonig genau öbi das scho komplett richtig as skeleton ahpasst han...

Chaschs echt mol dureluege und denn chömmers ja morn no churz zeme ahluege

2021-03-21 19:54 UTC, dvob requested changes

2021-03-21 19:54 UTC, dvob commented on http/incidence_client.go
> +	if filter.DateFrom != "" && filter.DateTo != "" { // if values are set
Make it possible to pass either DateFrom or DateTo.

2021-03-21 19:54 UTC, dvob commented on http/incidence_client.go
> +		log.Printf("The HTTP request failed with error %s\n", err)
If something fails return the error instead of logging it:
```
return nil, err
```
This way the caller can decide how to handle the error.

2021-03-21 19:54 UTC, dvob commented on http/incidence_client.go
> +		data, _ := ioutil.ReadAll(response.Body)
Check error of ReadAll

2021-03-21 19:54 UTC, dvob commented on http/incidence_client.go
> +var url = "https://" + switchServers[6] + "/incidences/"
Don't configure `url` as a global value. This way it's almost impossible to access multiple canton services. We probably want a field `baseURL` in the IncidenceClient struct. Then we can instantiate a IncidenceClient with an individual URL for each canton service:
```
type IncidenceClient struct {
    baseURL string
}

NewIncidenceClient(baseURL string) *IncidenceClient {
      return &IncidenceClient{
                   baseURL: baseURL,
      }
}
```
Then you can use the URL in the `GetIncidences` method with `i.baseURL`.

2021-03-21 19:54 UTC, dvob commented on http/incidence_client.go
> +	}
Do not overwrite the variable `url`. Otherwise if you call GetIncidences a second time you would get `url + idOfFirstCall + "/" + idOfSecondCall + "/"`

2021-03-22 13:23 UTC, livionaef commented on http/incidence_client.go
> +	if filter.DateFrom != "" && filter.DateTo != "" { // if values are set
Does it make sense to only pass one of them? I thought that it only makes sense when both of them are passed

2021-03-22 13:56 UTC, livionaef commented on http/incidence_client.go
> +	}
Should I get `var url = i.baseURL`  and then concat it like this `url += strconv.Itoa(filter.BFSID) + "/"` ?
Or is there a better way to do this?

2021-03-22 16:05 UTC, dvob approved these changes

2021-03-22 16:05 UTC, dvob commented on http/incidence_client.go
> +	if filter.DateFrom != "" && filter.DateTo != "" { // if values are set
Don't know, but I would say it make sense. If you for example only pass DateFrom you want all incidences from a certain date until today.
But we can leave it like this and implement it later if we really need it.

2021-03-22 16:05 UTC, dvob commented on http/incidence_client.go
> +	}
lgtm

2021-03-22 16:06 UTC, merged